import './globals.css';

import type { Metadata } from 'next';
import { Syne } from 'next/font/google';

import Sidebar from '@/ui/layout/sidebar';

const geistMono = Syne({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${geistMono.className} flex items-start antialiased`}>
        <Sidebar />
        <div className="w-4/5">{children}</div>
      </body>
    </html>
  );
}
